version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/eschool
      - SPRING_DATASOURCE_USERNAME=eschool
      - SPRING_DATASOURCE_PASSWORD=eschool
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=eschool
      - POSTGRES_USER=eschool
      - POSTGRES_PASSWORD=eschool
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  postgres_data:
